import nodemailer from 'nodemailer'
import type { Transporter } from 'nodemailer'
import { settingsService } from './settings.service'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface SmtpConfig {
  host: string
  port: number
  secure: boolean
  user: string
  password: string
  fromName: string
  fromAddress: string
}

export interface SendEmailOptions {
  to: string
  subject: string
  html: string
  /** Optional plain-text fallback */
  text?: string
}

export interface EmailResult {
  success: boolean
  error?: string
}

// ─── Config loader ─────────────────────────────────────────────────────────────

/** Load SMTP config from the settings table. Returns null if not configured. */
function loadSmtpConfig(): SmtpConfig | null {
  const host = settingsService.get('emailHost')
  const user = settingsService.get('emailUser')
  const password = settingsService.get('emailPassword')

  if (!host || !user || !password) return null

  return {
    host,
    port: parseInt(settingsService.get('emailPort') || '587', 10),
    secure: settingsService.get('emailSecure') === 'true',
    user,
    password,
    fromName: settingsService.get('emailFromName') || 'Kinetix POS',
    fromAddress: settingsService.get('emailFromAddress') || user,
  }
}

/** Build a nodemailer transporter from an SmtpConfig. */
function buildTransporter(cfg: SmtpConfig): Transporter {
  return nodemailer.createTransport({
    host: cfg.host,
    port: cfg.port,
    secure: cfg.secure,
    auth: { user: cfg.user, pass: cfg.password },
    // Allow self-signed / business SMTP certificates
    tls: { rejectUnauthorized: false },
    // 10 s connection timeout — avoids hanging the renderer
    connectionTimeout: 10_000,
    greetingTimeout: 10_000,
    socketTimeout: 15_000,
  })
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Send a receipt email to a customer.
 * @param to   Recipient email address
 * @param html Receipt HTML generated by buildReceiptHtml()
 * @param orderNumber Order number shown in subject line
 */
export async function sendReceiptEmail(
  to: string,
  html: string,
  orderNumber: string
): Promise<EmailResult> {
  const cfg = loadSmtpConfig()
  if (!cfg) return { success: false, error: 'Email not configured. Add SMTP settings in Settings → Email.' }

  try {
    const transporter = buildTransporter(cfg)
    await transporter.sendMail({
      from: `"${cfg.fromName}" <${cfg.fromAddress}>`,
      to,
      subject: `Your receipt — Order #${orderNumber}`,
      html,
      text: `Thank you for your purchase. Order #${orderNumber}.`,
    })
    return { success: true }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    return { success: false, error: msg }
  }
}

/**
 * Send an invoice email to a customer.
 * @param to   Recipient email address
 * @param html Invoice HTML
 * @param orderNumber Order number shown in subject line
 */
export async function sendInvoiceEmail(
  to: string,
  html: string,
  orderNumber: string
): Promise<EmailResult> {
  const cfg = loadSmtpConfig()
  if (!cfg) return { success: false, error: 'Email not configured. Add SMTP settings in Settings → Email.' }

  try {
    const transporter = buildTransporter(cfg)
    await transporter.sendMail({
      from: `"${cfg.fromName}" <${cfg.fromAddress}>`,
      to,
      subject: `Invoice — Order #${orderNumber}`,
      html,
      text: `Please find your invoice for Order #${orderNumber} attached.`,
    })
    return { success: true }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    return { success: false, error: msg }
  }
}

/**
 * Test SMTP connection using the provided config (not from DB — for the Settings test button).
 */
export async function testSmtpConnection(cfg: SmtpConfig): Promise<EmailResult> {
  try {
    const transporter = buildTransporter(cfg)
    await transporter.verify()
    return { success: true }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    return { success: false, error: msg }
  }
}
